# .platform.app.yaml
name: front
type: php:8.2
disk: 256

web:
  locations:
    "/":
      root: ""
      index:
        - index.php
        - index.html
      expires: 1h
      passthru: "/index.php" # fallback SPA -> renvoie vers index.php

build:
  flavor: none

hooks:
  build: |
    true
  deploy: |
    true

variables:
  env:
    APP_ENV: "prod"
    APP_DEBUG: "0"
